# Generated by Django 5.0.14 on 2026-08-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_pedidoloja_codigo_pedido_sankhya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localestoqueecommerce',
            name='codigo_local',
            field=models.CharField(help_text='Código numérico do local no Sankhya (CODLOCAL), enviado como inteiro na API.', max_length=12, verbose_name='Código do local'),
        ),
    ]
