# Generated by Django 5.0.14 on 2026-09-10 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0037_notacancelada'),
        ('ecommerce', '0017_alter_localestoqueecommerce_codigo_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=160, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('warning', 'Atenção'), ('danger', 'Urgente'), ('success', 'Positivo')], db_index=True, default='warning', max_length=16, verbose_name='Tipo')),
                ('data_inicio', models.DateField(db_index=True, verbose_name='Data de início')),
                ('data_fim', models.DateField(db_index=True, verbose_name='Data de fim')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Opcional. Ex.: 12:00 para aparecer todos os dias a partir do meio-dia. Vazio = desde 00:00.', null=True, verbose_name='Horário de início')),
                ('hora_fim', models.TimeField(blank=True, help_text='Opcional. Vazio = até o fim do dia. Use com o horário de início para uma janela (ex.: 12:00–18:00).', null=True, verbose_name='Horário de fim')),
                ('ordem', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(blank=True, help_text='Deixe em branco para exibir o alerta a todos os clientes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_loja', to='api_sankhya.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Alerta da loja',
                'verbose_name_plural': 'Alertas da loja',
                'ordering': ['ordem', '-criado_em'],
                'indexes': [models.Index(fields=['ativo', 'data_inicio', 'data_fim'], name='ecommerce_a_ativo_08156b_idx')],
            },
        ),
    ]
