# Generated by Django 5.0.14 on 2026-09-10 09:20

import django.db.models.deletion
from django.db import migrations, models


def copiar_cliente_fk_para_m2m(apps, schema_editor):
    AlertaLoja = apps.get_model('ecommerce', 'AlertaLoja')
    for alerta in AlertaLoja.objects.exclude(cliente_id=None).only('id', 'cliente_id'):
        alerta.clientes.add(alerta.cliente_id)


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0037_notacancelada'),
        ('ecommerce', '0018_alerta_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaloja',
            name='cliente',
            field=models.ForeignKey(
                blank=True,
                help_text='Deixe em branco para exibir o alerta a todos os clientes.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='alertas_loja_fk',
                to='api_sankhya.cliente',
                verbose_name='Cliente',
            ),
        ),
        migrations.AddField(
            model_name='alertaloja',
            name='clientes',
            field=models.ManyToManyField(
                blank=True,
                help_text='Vazio = todos os clientes. Vincule um ou mais para restringir o alerta.',
                related_name='alertas_loja',
                to='api_sankhya.cliente',
                verbose_name='Clientes',
            ),
        ),
        migrations.RunPython(copiar_cliente_fk_para_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='alertaloja',
            name='cliente',
        ),
    ]
