# Generated by Django 5.0.14 on 2026-10-06 15:14

import ecommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_banner_imagem_mobile_upload_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoimagem',
            name='imagem_secundaria',
            field=models.ImageField(blank=True, help_text='Opcional. Na loja, o cliente pode passar da foto principal para esta. Se ficar vazia, a vitrine mostra só a imagem principal.', upload_to=ecommerce.models._produto_imagem_upload_to, verbose_name='Segunda imagem'),
        ),
        migrations.AlterField(
            model_name='produtoimagem',
            name='imagem',
            field=models.ImageField(help_text='Foto principal do produto. É sempre a primeira a aparecer na loja.', upload_to=ecommerce.models._produto_imagem_upload_to, verbose_name='Imagem principal'),
        ),
    ]
