# Generated by Django 5.0.14 on 2025-04-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('ajudante', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ajudante',
                'verbose_name_plural': 'Ajudantes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('veiculo', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='secao',
            options={'ordering': ['id'], 'verbose_name': 'Seção', 'verbose_name_plural': 'Seções'},
        ),
    ]
