# Generated by Django 5.0.14 on 2025-04-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0002_ajudante_veiculo_alter_secao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajudante',
            name='sincronizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sincronizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motorista',
            name='sincronizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sincronizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='sincronizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='sincronizado',
            field=models.BooleanField(default=False),
        ),
    ]
