# Generated by Django 5.0.14 on 2025-04-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0004_ajudante_apelido_motorista_apelido_vendedor_apelido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajudante',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
