# Generated by Django 5.0.14 on 2025-04-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0005_ajudante_cpf_cliente_cnpj_motorista_cpf_vendedor_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fantasia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
