# Generated by Django 5.0.14 on 2025-04-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0006_cliente_fantasia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajudante',
            options={'ordering': ['id'], 'verbose_name': 'Integração - Ajudante', 'verbose_name_plural': 'Integração - Ajudantes'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id'], 'verbose_name': 'Integração - Cliente', 'verbose_name_plural': 'Integração - Clientes'},
        ),
        migrations.AlterModelOptions(
            name='clientevendedor',
            options={'ordering': ['id'], 'verbose_name': 'BI - Cliente Vendedor', 'verbose_name_plural': 'BI - Clientes Vendedores'},
        ),
        migrations.AlterModelOptions(
            name='motorista',
            options={'ordering': ['id'], 'verbose_name': 'Integração - Motorista', 'verbose_name_plural': 'Integração - Motoristas'},
        ),
        migrations.AlterModelOptions(
            name='operacao',
            options={'ordering': ['id'], 'verbose_name': 'BI - Operação', 'verbose_name_plural': 'BI - Operações'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['id'], 'verbose_name': 'Integração - Pedido', 'verbose_name_plural': 'Integração - Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='secao',
            options={'ordering': ['id'], 'verbose_name': 'BI - Seção', 'verbose_name_plural': 'BI - Seções'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['id'], 'verbose_name': 'Integração - Veículo', 'verbose_name_plural': 'Integração - Veículos'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'ordering': ['id'], 'verbose_name': 'BI - Vendedor', 'verbose_name_plural': 'BI - Vendedores'},
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='veiculo',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='codigo',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano_fabricacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano_modelo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='campo_alt',
            field=models.CharField(blank=True, default='NEW_762', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='codigo_erp',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='filial',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='km_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='peso_max_entregas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='qtd_max_entregas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='qtd_pallets_veiculo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='seq_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='status_combustivel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='status_inicial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='velocidade_maxima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='volume_max_entregas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
