# Generated by Django 5.0.14 on 2025-04-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0007_alter_ajudante_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
