# Generated by Django 5.0.14 on 2025-04-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0008_delete_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_alt', models.CharField(blank=True, default='NEW_762', max_length=10, null=True)),
                ('seq_id', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_erp', models.CharField(max_length=20, unique=True)),
                ('placa', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('km_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('ano_modelo', models.IntegerField(blank=True, null=True)),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True)),
                ('qtd_max_entregas', models.IntegerField(blank=True, null=True)),
                ('velocidade_maxima', models.IntegerField(blank=True, null=True)),
                ('status_combustivel', models.CharField(blank=True, max_length=20, null=True)),
                ('status_inicial', models.CharField(blank=True, max_length=20, null=True)),
                ('peso_max_entregas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume_max_entregas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qtd_pallets_veiculo', models.IntegerField(blank=True, null=True)),
                ('filial', models.CharField(max_length=10)),
                ('sincronizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integração - Veículo',
                'verbose_name_plural': 'Integração - Veículos',
                'ordering': ['id'],
            },
        ),
    ]
