# Generated by Django 5.0.14 on 2025-04-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0009_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='status_combustivel',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_combustivel',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Flex', 'Flex'), ('Eletrico', 'Eletrico'), ('Alcool', 'Alcool'), ('Outros', 'Outros')], default='Diesel', max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status_inicial',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=20),
        ),
    ]
