# Generated by Django 5.0.14 on 2025-04-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0010_remove_veiculo_status_combustivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(blank=True, choices=[('Volkswagen', 'Volkswagen'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('fiat', 'Fiat'), ('hyundai', 'Hyundai'), ('nissan', 'Nissan'), ('peugeot', 'Peugeot'), ('renault', 'Renault'), ('toyota', 'Toyota'), ('volvo', 'Volvo'), ('mercedes', 'Mercedes')], max_length=50, null=True),
        ),
    ]
