# Generated by Django 5.0.14 on 2025-04-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0011_alter_veiculo_modelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Motorista',
        ),
    ]
