# Generated by Django 5.0.14 on 2025-04-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0012_delete_motorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_alt', models.CharField(blank=True, default='NEW_825', max_length=10, null=True)),
                ('seq_id', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_erp', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('tipo', models.CharField(choices=[('Motorista', 'Motorista'), ('Ajudante', 'Ajudante')], max_length=20)),
                ('sincronizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integração - Funcionário',
                'verbose_name_plural': 'Integração - Funcionários',
                'ordering': ['id'],
            },
        ),
    ]
