# Generated by Django 5.0.14 on 2025-04-20 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0013_motorista'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Motorista',
            new_name='Funcionario',
        ),
    ]
