# Generated by Django 5.0.14 on 2025-04-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0014_rename_motorista_funcionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ajudante',
        ),
    ]
