# Generated by Django 5.0.14 on 2025-04-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0015_delete_ajudante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
