# Generated by Django 5.0.14 on 2025-04-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0017_pedido_itempedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dt_list_nf',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da Coleta'),
        ),
    ]
