# Generated by Django 5.0.14 on 2025-04-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0018_alter_pedido_dt_list_nf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='permite_retira_cliente',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, null=True, verbose_name='Permite Retirada'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='praca_cod_erp',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Código Praça'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='retem_icms_cliente',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, null=True, verbose_name='Retém ICMS'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='rota_cod_erp',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Código Rota'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='vlr_tits_vencer_cliente',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=18, null=True, verbose_name='Títulos a Vencer'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='vlr_tits_vencido_cliente',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=18, null=True, verbose_name='Títulos Vencidos'),
        ),
    ]
