# Generated by Django 5.0.14 on 2025-04-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0020_pedido_created_at_pedido_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='sincronizado',
            field=models.BooleanField(default=False),
        ),
    ]
