# Generated by Django 5.0.14 on 2025-04-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0021_pedido_sincronizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cnpj_cliente',
            field=models.CharField(max_length=14, verbose_name='CNPJ/CPF'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descr_cliente',
            field=models.CharField(max_length=100, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='razao_cliente',
            field=models.CharField(max_length=100, verbose_name='Razão Social'),
        ),
    ]
