# Generated by Django 5.0.14 on 2025-04-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0022_alter_pedido_cnpj_cliente_alter_pedido_descr_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
    ]
