# Generated by Django 5.0.14 on 2025-04-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0023_alter_itempedido_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dt_list_nf',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Coleta'),
        ),
    ]
