# Generated by Django 5.0.14 on 2025-04-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0024_alter_pedido_dt_list_nf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pedido'),
        ),
    ]
