# Generated by Django 5.0.14 on 2025-05-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0026_alter_pedido_data_cadastro_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='tipo_veiculo',
            field=models.CharField(blank=True, choices=[('Caminhão', 'Caminhão'), ('Furgão', 'Furgão'), ('Van', 'Van'), ('Carro', 'Carro')], max_length=20, null=True),
        ),
    ]
