# Generated by Django 5.0.14 on 2025-05-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0027_veiculo_tipo_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='flat_tecnico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
