# Generated by Django 5.0.14 on 2025-05-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0028_cliente_flat_tecnico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='flat_tecnico',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='flat_tecnico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
