# Generated by Django 5.0.14 on 2025-05-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0029_remove_cliente_flat_tecnico_vendedor_flat_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='peso_max_entregas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='qtd_max_entregas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='qtd_pallets_veiculo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='volume_max_entregas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
