# Generated by Django 5.0.14 on 2025-05-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0030_alter_veiculo_peso_max_entregas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='km_atual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
