# Generated by Django 5.0.14 on 2025-05-11 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0032_funcionario_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=100, verbose_name='Origem')),
                ('obs', models.TextField(verbose_name='Observação')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'ordering': ['-created'],
            },
        ),
    ]
