# Generated by Django 5.0.14 on 2025-05-27 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0033_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteERP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_alt', models.CharField(default='NEW_59', max_length=10)),
                ('seq_id', models.CharField(max_length=10)),
                ('codigo_cliente', models.CharField(max_length=10)),
                ('filial_padrao', models.CharField(max_length=10)),
                ('descr_cliente', models.CharField(max_length=100)),
                ('razao_cliente', models.CharField(max_length=100)),
                ('cnpj_cpf_cliente', models.CharField(max_length=14)),
                ('cliente_cod_rota_erp', models.CharField(max_length=10)),
                ('cliente_descricao_rota', models.CharField(max_length=100)),
                ('cod_segmento', models.CharField(max_length=10)),
                ('descr_segmento', models.CharField(max_length=50)),
                ('cep_cliente', models.CharField(max_length=8)),
                ('end_cliente', models.CharField(max_length=200)),
                ('num_end_cliente', models.CharField(max_length=10)),
                ('bairro_cliente', models.CharField(max_length=100)),
                ('cidade_cliente', models.CharField(max_length=100)),
                ('uf_cliente', models.CharField(max_length=2)),
                ('email1_cliente', models.EmailField(blank=True, max_length=100, null=True)),
                ('email2_cliente', models.EmailField(blank=True, max_length=100, null=True)),
                ('email3_cliente', models.EmailField(blank=True, max_length=100, null=True)),
                ('tel1_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('tel2_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('tel3_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('data_cadastro_cliente', models.DateTimeField()),
                ('vlr_credito_cliente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_disp_cliente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vlr_tits_vencido_cliente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vlr_tits_vencer_cliente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status_cred_cliente', models.CharField(max_length=20)),
                ('data_ult_compra', models.DateTimeField(blank=True, null=True)),
                ('forma_pgto_cliente', models.CharField(max_length=50)),
                ('turnos_entrega', models.CharField(max_length=100)),
                ('prioritario', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1)),
                ('bloqueiosefaz', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1)),
                ('rede_loja_cliente', models.CharField(max_length=10)),
                ('sincronizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integração - Cliente ERP',
                'verbose_name_plural': 'Integração - Clientes ERP',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.CreateModel(
            name='EnderecoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_end_erp', models.CharField(max_length=20)),
                ('cod_praca_erp', models.CharField(max_length=20)),
                ('descr_praca_erp', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=200)),
                ('num_end', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=8)),
                ('ref_entrega', models.CharField(blank=True, max_length=200, null=True)),
                ('sn_padrao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1)),
                ('latitude', models.DecimalField(decimal_places=7, default=0, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=7, default=0, max_digits=18)),
                ('sincronizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clienteERP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='controleBI.clienteerp')),
            ],
            options={
                'verbose_name': 'Endereço do Cliente',
                'verbose_name_plural': 'Endereços dos Clientes',
                'ordering': ['clienteERP', '-sn_padrao'],
            },
        ),
    ]
