# Generated by Django 5.0.14 on 2025-05-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0036_alter_clienteerp_cnpj_cpf_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteerp',
            name='vlr_tits_vencer_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clienteerp',
            name='vlr_tits_vencido_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
