# Generated by Django 5.0.14 on 2025-05-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0037_alter_clienteerp_vlr_tits_vencer_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteerp',
            name='bloqueiosefaz',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='clienteerp',
            name='prioritario',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, null=True),
        ),
    ]
