# Generated by Django 5.0.14 on 2025-05-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0038_alter_clienteerp_bloqueiosefaz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecocliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='cod_end_erp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='cod_praca_erp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='descr_praca_erp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='end',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='num_end',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='sn_padrao',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
