# Generated by Django 5.0.14 on 2025-05-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0039_alter_enderecocliente_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='cd_cargo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='nm_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
