# Generated by Django 5.0.14 on 2025-06-26 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0041_praca_clienteerp_praca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteerp',
            name='praca',
        ),
        migrations.AddField(
            model_name='enderecocliente',
            name='praca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controleBI.praca', verbose_name='Praca'),
        ),
    ]
