# Generated by Django 5.0.14 on 2026-03-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0044_usuario_cliente_sankhya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(choices=[('cliente', 'Cliente (e-commerce)'), ('comercial', 'Comercial (painel BI)'), ('administrador', 'Administrador do sistema (painel BI)')], default='comercial', max_length=20, verbose_name='Perfil'),
        ),
    ]
