# Generated by Django 5.0.14 on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleBI', '0045_alter_perfilusuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(
                choices=[
                    ('cliente', 'Cliente (e-commerce)'),
                    ('comercial', 'Comercial (painel BI)'),
                    ('gerente_comercial', 'Gerente comercial (painel BI)'),
                    ('administrador', 'Administrador do sistema (painel BI)'),
                ],
                default='comercial',
                max_length=20,
                verbose_name='Perfil',
            ),
        ),
    ]
