"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'controleBI',
    'api_sankhya',
    'pwa',
    'ecommerce',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'ecommerce.middleware.EcommerceLoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ecommerce.context_processors.ecommerce_nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# Se DATABASE_URL existir (Railway/produção), usa PostgreSQL via dj_database_url.
# Caso contrário, usa SQL Server local (desenvolvimento).
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('ENGINE'),
            'NAME': os.getenv('DATABASE'),
            'USER': os.getenv('USER_DB'),
            'PASSWORD': os.getenv('PASSWORD_DB'),
            'HOST': os.getenv('HOST'),
            'PORT': os.getenv('PORT'),
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
                'TrustServerCertificate': 'yes',
                'unicode_results': True,
                'extra_params': 'tds_version=7.3'
            },
        },
        'erp': {
            'ENGINE': os.getenv('ENGINE'),
            'NAME': os.getenv('DATABASE_ERP'),
            'USER': os.getenv('USER_ERP'),
            'PASSWORD': os.getenv('PASSWORD_ERP'),
            'HOST': os.getenv('HOST_ERP'),
            'PORT': os.getenv('PORT_ERP'),
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
                'TrustServerCertificate': 'yes',
                'unicode_results': True,
                'extra_params': 'tds_version=7.3'
            },
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
MEDIA_URL = '/media/'
RAILWAY_VOLUME_MOUNT_PATH = os.getenv('RAILWAY_VOLUME_MOUNT_PATH')
MEDIA_ROOT = (
    os.getenv('MEDIA_ROOT')
    or (
        os.path.join(RAILWAY_VOLUME_MOUNT_PATH, 'media')
        if RAILWAY_VOLUME_MOUNT_PATH
        else os.path.join(BASE_DIR, 'media')
    )
)

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# WhiteNoise: servir arquivos estáticos em produção (Railway, etc.)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Progressive Web App (django-pwa) — vitrine / loja em /ecommerce/
PWA_APP_NAME = 'PMIX Shop'
PWA_APP_DESCRIPTION = 'Loja online responsiva e instalável (PWA).'
PWA_APP_THEME_COLOR = '#0ea5e9'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'portrait-primary'
PWA_APP_START_URL = '/ecommerce/'
PWA_APP_FETCH_URL = '/ecommerce/'
PWA_APP_DEBUG_MODE = DEBUG
PWA_APP_ICONS = [
    {'src': '/static/ecommerce/icons/icon-192.png', 'sizes': '192x192', 'type': 'image/png'},
    {'src': '/static/ecommerce/icons/icon-512.png', 'sizes': '512x512', 'type': 'image/png'},
]
PWA_APP_SPLASH_SCREEN = []

# Authentication settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = '/accounts/login/' 



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, "debug.log"),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}