# Generated by Django 5.0.14 on 2026-02-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_veiculo', models.IntegerField(unique=True, verbose_name='Código do Veículo')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa')),
                ('marca_modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca/Modelo')),
                ('numero_motor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Motor')),
                ('renavam', models.CharField(blank=True, max_length=20, null=True, verbose_name='RENAVAM')),
                ('chassis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chassis')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria')),
                ('peso_maximo', models.IntegerField(blank=True, null=True, verbose_name='Peso Máximo')),
                ('combustivel', models.IntegerField(blank=True, null=True, verbose_name='Combustível')),
                ('cor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor')),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True, verbose_name='Ano de Fabricação')),
                ('ano_modelo', models.IntegerField(blank=True, null=True, verbose_name='Ano do Modelo')),
                ('codigo_cidade', models.IntegerField(blank=True, null=True, verbose_name='Código da Cidade')),
                ('nome_cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Cidade')),
                ('codigo_funcionario', models.IntegerField(blank=True, null=True, verbose_name='Código do Funcionário')),
                ('nome_funcionario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Funcionário')),
                ('codigo_motorista', models.IntegerField(blank=True, null=True, verbose_name='Código do Motorista')),
                ('nome_motorista', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Motorista')),
                ('codigo_parceiro', models.IntegerField(blank=True, null=True, verbose_name='Código do Parceiro')),
                ('nome_parceiro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Parceiro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Veículo Sankhya',
                'verbose_name_plural': 'Veículos Sankhya',
                'db_table': 'sankhya_veiculo',
                'ordering': ['codigo_veiculo'],
                'indexes': [models.Index(fields=['codigo_veiculo'], name='sankhya_vei_codigo__34ca5c_idx'), models.Index(fields=['placa'], name='sankhya_vei_placa_363117_idx'), models.Index(fields=['ativo'], name='sankhya_vei_ativo_4e3433_idx')],
            },
        ),
    ]
