# Generated by Django 5.0.14 on 2026-02-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empresa', models.IntegerField(unique=True, verbose_name='Código da Empresa')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social')),
                ('razao_abreviada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razão Abreviada')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ/CPF')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('homepage', models.URLField(blank=True, null=True, verbose_name='Homepage')),
                ('codigo_logradouro', models.IntegerField(blank=True, null=True, verbose_name='Código do Logradouro')),
                ('nome_logradouro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('codigo_bairro', models.IntegerField(blank=True, null=True, verbose_name='Código do Bairro')),
                ('nome_bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Bairro')),
                ('codigo_cidade', models.IntegerField(blank=True, null=True, verbose_name='Código da Cidade')),
                ('nome_cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Cidade')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('codigo_empresa_matriz', models.IntegerField(blank=True, null=True, verbose_name='Código da Empresa Matriz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Empresa Sankhya',
                'verbose_name_plural': 'Empresas Sankhya',
                'db_table': 'sankhya_empresa',
                'ordering': ['codigo_empresa'],
                'indexes': [models.Index(fields=['codigo_empresa'], name='sankhya_emp_codigo__30f865_idx'), models.Index(fields=['cnpj_cpf'], name='sankhya_emp_cnpj_cp_f0222f_idx'), models.Index(fields=['codigo_empresa_matriz'], name='sankhya_emp_codigo__eb42d6_idx')],
            },
        ),
    ]
