# Generated by Django 5.0.14 on 2026-02-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0002_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cidade', models.IntegerField(unique=True, verbose_name='Código da Cidade')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('codigo_regiao', models.IntegerField(blank=True, null=True, verbose_name='Código da Região')),
                ('nome_regiao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Região')),
                ('nome_correio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Correio')),
                ('codigo_municipio_fiscal', models.IntegerField(blank=True, null=True, verbose_name='Código Município Fiscal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Cidade Sankhya',
                'verbose_name_plural': 'Cidades Sankhya',
                'db_table': 'sankhya_cidade',
                'ordering': ['nome', 'uf'],
                'indexes': [models.Index(fields=['codigo_cidade'], name='sankhya_cid_codigo__6478d9_idx'), models.Index(fields=['uf'], name='sankhya_cid_uf_1304ed_idx'), models.Index(fields=['codigo_regiao'], name='sankhya_cid_codigo__f7c13f_idx'), models.Index(fields=['codigo_municipio_fiscal'], name='sankhya_cid_codigo__a4eb61_idx')],
            },
        ),
    ]
