# Generated by Django 5.0.14 on 2026-02-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0003_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_logradouro', models.IntegerField(unique=True, verbose_name='Código do Logradouro')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('descricao_correio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição Correio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Logradouro Sankhya',
                'verbose_name_plural': 'Logradouros Sankhya',
                'db_table': 'sankhya_logradouro',
                'ordering': ['nome', 'tipo'],
                'indexes': [models.Index(fields=['codigo_logradouro'], name='sankhya_log_codigo__bdd133_idx'), models.Index(fields=['nome'], name='sankhya_log_nome_752368_idx'), models.Index(fields=['tipo'], name='sankhya_log_tipo_d588f0_idx')],
            },
        ),
    ]
