# Generated by Django 5.0.14 on 2026-02-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0004_logradouro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_bairro', models.IntegerField(unique=True, verbose_name='Código do Bairro')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('nome_regiao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Região')),
                ('nome_correio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Correio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Bairro Sankhya',
                'verbose_name_plural': 'Bairros Sankhya',
                'db_table': 'sankhya_bairro',
                'ordering': ['nome', 'nome_regiao'],
                'indexes': [models.Index(fields=['codigo_bairro'], name='sankhya_bai_codigo__cc6ab3_idx'), models.Index(fields=['nome'], name='sankhya_bai_nome_3e1d3e_idx'), models.Index(fields=['nome_regiao'], name='sankhya_bai_nome_re_370b1c_idx')],
            },
        ),
    ]
