# Generated by Django 5.0.14 on 2026-02-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0005_bairro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vendedor', models.IntegerField(unique=True, verbose_name='Código do Vendedor')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.IntegerField(blank=True, null=True, verbose_name='Tipo')),
                ('comissao_gerencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comissão Gerência')),
                ('comissao_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comissão Venda')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('codigo_empresa', models.IntegerField(blank=True, null=True, verbose_name='Código da Empresa')),
                ('nome_empresa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Empresa')),
                ('codigo_parceiro', models.IntegerField(blank=True, null=True, verbose_name='Código do Parceiro')),
                ('nome_parceiro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Parceiro')),
                ('codigo_funcionario', models.IntegerField(blank=True, null=True, verbose_name='Código do Funcionário')),
                ('nome_funcionario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Funcionário')),
                ('codigo_gerente', models.IntegerField(blank=True, null=True, verbose_name='Código do Gerente')),
                ('nome_gerente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Gerente')),
                ('codigo_centro_resultado', models.IntegerField(blank=True, null=True, verbose_name='Código do Centro de Resultado')),
                ('nome_centro_resultado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Centro de Resultado')),
                ('codigo_regiao', models.IntegerField(blank=True, null=True, verbose_name='Código da Região')),
                ('nome_regiao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Região')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Vendedor Sankhya',
                'verbose_name_plural': 'Vendedores Sankhya',
                'db_table': 'sankhya_vendedor',
                'ordering': ['nome', 'codigo_vendedor'],
                'indexes': [models.Index(fields=['codigo_vendedor'], name='sankhya_ven_codigo__2ed6dd_idx'), models.Index(fields=['nome'], name='sankhya_ven_nome_e5daaa_idx'), models.Index(fields=['ativo'], name='sankhya_ven_ativo_1f3161_idx'), models.Index(fields=['codigo_empresa'], name='sankhya_ven_codigo__227db0_idx'), models.Index(fields=['codigo_gerente'], name='sankhya_ven_codigo__f1844e_idx')],
            },
        ),
    ]
