# Generated by Django 5.0.14 on 2026-02-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0006_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.IntegerField(unique=True, verbose_name='Código do Cliente')),
                ('tipo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ/CPF')),
                ('ie_rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='IE/RG')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome')),
                ('razao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('telefone_ddd', models.CharField(blank=True, max_length=3, null=True, verbose_name='DDD')),
                ('telefone_numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Limite de Crédito')),
                ('grupo_autorizacao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Grupo Autorização')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('codigo_ibge', models.BigIntegerField(blank=True, null=True, verbose_name='Código IBGE')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Cliente Sankhya',
                'verbose_name_plural': 'Clientes Sankhya',
                'db_table': 'sankhya_cliente',
                'ordering': ['nome', 'codigo_cliente'],
                'indexes': [models.Index(fields=['codigo_cliente'], name='sankhya_cli_codigo__94b3bb_idx'), models.Index(fields=['cnpj_cpf'], name='sankhya_cli_cnpj_cp_a9b04c_idx'), models.Index(fields=['nome'], name='sankhya_cli_nome_fa7fef_idx'), models.Index(fields=['tipo'], name='sankhya_cli_tipo_0d0cb9_idx'), models.Index(fields=['uf'], name='sankhya_cli_uf_dc098c_idx'), models.Index(fields=['cidade'], name='sankhya_cli_cidade_b0d57d_idx')],
            },
        ),
    ]
