# Generated by Django 5.0.14 on 2026-02-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0007_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone_ddd',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='DDD'),
        ),
    ]
