# Generated by Django 5.0.14 on 2026-02-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0008_alter_cliente_telefone_ddd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_motorista', models.IntegerField(unique=True, verbose_name='Código do Motorista')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('cnh', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNH')),
                ('categoria_cnh', models.CharField(blank=True, max_length=10, null=True, verbose_name='Categoria CNH')),
                ('data_vencimento_cnh', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Vencimento CNH')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('codigo_ibge', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código IBGE')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Motorista Sankhya',
                'verbose_name_plural': 'Motoristas Sankhya',
                'db_table': 'sankhya_motorista',
                'ordering': ['nome', 'codigo_motorista'],
                'indexes': [models.Index(fields=['codigo_motorista'], name='sankhya_mot_codigo__4ac9dd_idx'), models.Index(fields=['cpf'], name='sankhya_mot_cpf_18d16e_idx'), models.Index(fields=['nome'], name='sankhya_mot_nome_d38b11_idx'), models.Index(fields=['cnh'], name='sankhya_mot_cnh_38295c_idx'), models.Index(fields=['uf'], name='sankhya_mot_uf_b60de9_idx'), models.Index(fields=['cidade'], name='sankhya_mot_cidade_74c947_idx')],
            },
        ),
    ]
