# Generated by Django 5.0.14 on 2026-02-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0009_motorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.IntegerField(verbose_name='Código do Produto')),
                ('codigo_local_estoque', models.IntegerField(default=0, verbose_name='Código Local Estoque')),
                ('controle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Controle')),
                ('unidade', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidade')),
                ('codigo_tabela', models.IntegerField(verbose_name='Código da Tabela')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Preço Sankhya',
                'verbose_name_plural': 'Preços Sankhya',
                'db_table': 'sankhya_preco',
                'ordering': ['codigo_produto', 'codigo_tabela', 'codigo_local_estoque'],
                'indexes': [models.Index(fields=['codigo_produto'], name='sankhya_pre_codigo__4453d9_idx'), models.Index(fields=['codigo_tabela'], name='sankhya_pre_codigo__134c45_idx'), models.Index(fields=['codigo_local_estoque'], name='sankhya_pre_codigo__19df56_idx'), models.Index(fields=['codigo_produto', 'codigo_tabela'], name='sankhya_pre_codigo__76b2b9_idx')],
                'unique_together': {('codigo_produto', 'codigo_local_estoque', 'codigo_tabela')},
            },
        ),
    ]
