# Generated by Django 5.0.14 on 2026-02-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0010_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.IntegerField(unique=True, verbose_name='Código do Produto')),
                ('data_alteracao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Alteração')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento')),
                ('caracteristicas', models.TextField(blank=True, null=True, verbose_name='Características')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência')),
                ('codigo_grupo_produto', models.IntegerField(blank=True, null=True, verbose_name='Código Grupo Produto')),
                ('nome_grupo_produto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Grupo Produto')),
                ('volume', models.CharField(blank=True, max_length=10, null=True, verbose_name='Volume')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('decimais_valor', models.IntegerField(blank=True, null=True, verbose_name='Decimais Valor')),
                ('decimais_quantidade', models.IntegerField(blank=True, null=True, verbose_name='Decimais Quantidade')),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Peso Bruto')),
                ('agrupamento_minimo', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Agrupamento Mínimo')),
                ('quantidade_embalagem', models.IntegerField(blank=True, null=True, verbose_name='Quantidade Embalagem')),
                ('tipo_controle_estoque', models.IntegerField(blank=True, null=True, verbose_name='Tipo Controle Estoque')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('estoque_maximo', models.IntegerField(blank=True, null=True, verbose_name='Estoque Máximo')),
                ('estoque_minimo', models.IntegerField(blank=True, null=True, verbose_name='Estoque Mínimo')),
                ('homepage', models.URLField(blank=True, null=True, verbose_name='Homepage')),
                ('grupo_desconto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo Desconto')),
                ('referencia_fornecedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência Fornecedor')),
                ('usado_como', models.IntegerField(blank=True, null=True, verbose_name='Usado Como')),
                ('cnae', models.BigIntegerField(blank=True, null=True, verbose_name='CNAE')),
                ('metro_cubico', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Metro Cúbico')),
                ('altura', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Altura')),
                ('largura', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Largura')),
                ('espessura', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Espessura')),
                ('unidade_medida', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidade Medida')),
                ('utiliza_balanca', models.BooleanField(default=False, verbose_name='Utiliza Balança')),
                ('codigo_pais', models.IntegerField(blank=True, null=True, verbose_name='Código País')),
                ('ncm', models.CharField(blank=True, max_length=20, null=True, verbose_name='NCM')),
                ('cest', models.CharField(blank=True, max_length=20, null=True, verbose_name='CEST')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Produto Sankhya',
                'verbose_name_plural': 'Produtos Sankhya',
                'db_table': 'sankhya_produto',
                'ordering': ['nome', 'codigo_produto'],
                'indexes': [models.Index(fields=['codigo_produto'], name='sankhya_pro_codigo__804730_idx'), models.Index(fields=['nome'], name='sankhya_pro_nome_4167f7_idx'), models.Index(fields=['referencia'], name='sankhya_pro_referen_2430bd_idx'), models.Index(fields=['codigo_grupo_produto'], name='sankhya_pro_codigo__ef6513_idx'), models.Index(fields=['ativo'], name='sankhya_pro_ativo_31122b_idx'), models.Index(fields=['ncm'], name='sankhya_pro_ncm_f6e1bf_idx')],
            },
        ),
    ]
