# Generated by Django 5.0.14 on 2026-02-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0011_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_grupo_produto', models.IntegerField(unique=True, verbose_name='Código do Grupo Produto')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('codigo_grupo_produto_pai', models.IntegerField(blank=True, null=True, verbose_name='Código Grupo Produto Pai')),
                ('grau', models.IntegerField(blank=True, null=True, verbose_name='Grau')),
                ('grupo_icms', models.IntegerField(blank=True, null=True, verbose_name='Grupo ICMS')),
                ('analitico', models.BooleanField(default=False, verbose_name='Analítico')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Grupo Produto Sankhya',
                'verbose_name_plural': 'Grupos Produto Sankhya',
                'db_table': 'sankhya_grupo_produto',
                'ordering': ['nome', 'codigo_grupo_produto'],
                'indexes': [models.Index(fields=['codigo_grupo_produto'], name='sankhya_gru_codigo__651e61_idx'), models.Index(fields=['nome'], name='sankhya_gru_nome_50fc43_idx'), models.Index(fields=['codigo_grupo_produto_pai'], name='sankhya_gru_codigo__7ef7f4_idx'), models.Index(fields=['ativo'], name='sankhya_gru_ativo_9e1447_idx'), models.Index(fields=['grupo_icms'], name='sankhya_gru_grupo_i_597cf5_idx')],
            },
        ),
    ]
