# Generated by Django 5.0.14 on 2026-02-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0013_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entrega',
            field=models.BooleanField(default=False, verbose_name='Endereço de entrega'),
        ),
    ]
