# Generated by Django 5.0.14 on 2026-03-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0014_pedido_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codparc', models.IntegerField(verbose_name='Código Parceiro')),
                ('codcontato', models.IntegerField(verbose_name='Código Contato')),
                ('nomecontato', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Contato')),
                ('apelido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido')),
                ('codend', models.IntegerField(blank=True, null=True, verbose_name='Código Endereço')),
                ('numend', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Endereço')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('codbai', models.IntegerField(blank=True, null=True, verbose_name='Código Bairro')),
                ('codcid', models.IntegerField(blank=True, null=True, verbose_name='Código Cidade')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contato Sankhya',
                'verbose_name_plural': 'Contatos Sankhya',
                'db_table': 'sankhya_contato',
                'ordering': ['codparc', 'codcontato'],
                'indexes': [models.Index(fields=['codparc'], name='sankhya_con_codparc_cf7965_idx'), models.Index(fields=['codcontato'], name='sankhya_con_codcont_7ea2b1_idx'), models.Index(fields=['email'], name='sankhya_con_email_9058cb_idx'), models.Index(fields=['codcid'], name='sankhya_con_codcid_98487b_idx')],
                'unique_together': {('codparc', 'codcontato')},
            },
        ),
    ]
