# Generated by Django 5.0.14 on 2026-03-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0017_cidade_legado_dt_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='codigo_cidade',
            field=models.IntegerField(unique=True, verbose_name='Código da Cidade (CODCID)'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='codigo_regiao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código da Região (CODREG)'),
        ),
    ]
