# Generated by Django 5.0.14 on 2026-03-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0019_grupoproduto_mostrar_no_ecommerce'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='grupoproduto',
            new_name='sankhya_gru_ativo_3ffc9a_idx',
            old_name='sankhya_gru_ativo_m_6a8b2c_idx',
        ),
    ]
