# Generated by Django 5.0.14 on 2026-04-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0021_merge_0017_cliente_0020_grupo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cliente',
            new_name='sankhya_cli_codtab_0d4c78_idx',
            old_name='sankhya_cli_codtab_a28c70_idx',
        ),
        migrations.RenameIndex(
            model_name='cliente',
            new_name='sankhya_cli_codend_03c853_idx',
            old_name='sankhya_cli_codend_94f051_idx',
        ),
    ]
