# Generated by Django 5.0.14 on 2026-06-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_sankhya", "0028_pedido_unique_codigo_nota_empresa_origem"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaFiscal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nunota", models.IntegerField(unique=True, verbose_name="Nº único (NUNOTA)")),
                ("codigo_empresa", models.IntegerField(blank=True, null=True, verbose_name="Código Empresa (CODEMP)")),
                ("numero_nota", models.IntegerField(blank=True, null=True, verbose_name="Número NF (NUMNOTA)")),
                ("data_entrada_saida", models.DateField(blank=True, null=True, verbose_name="Data Entrada/Saída (DTENTSAI)")),
                ("data_negociacao", models.DateField(blank=True, null=True, verbose_name="Data Negociação (DTNEG)")),
                ("codigo_tipo_operacao", models.IntegerField(blank=True, null=True, verbose_name="Tipo Operação (CODTIPOPER)")),
                ("codigo_parceiro", models.IntegerField(blank=True, null=True, verbose_name="Parceiro (CODPARC)")),
                ("tipo_movimento", models.CharField(blank=True, max_length=10, null=True, verbose_name="Tipo Movimento (TIPMOV)")),
                ("pendente", models.CharField(blank=True, max_length=5, null=True, verbose_name="Pendente (PENDENTE)")),
                ("status_nfe", models.CharField(blank=True, max_length=30, null=True, verbose_name="Status NFe (STATUSNFE)")),
                ("status_nota", models.CharField(blank=True, max_length=30, null=True, verbose_name="Status Nota (STATUSNOTA)")),
                ("aprovado", models.CharField(blank=True, max_length=5, null=True, verbose_name="Aprovado (APROVADO)")),
                ("dtalter", models.CharField(blank=True, max_length=50, null=True, verbose_name="Data Alteração (DTALTER)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Nota Fiscal Sankhya",
                "verbose_name_plural": "Notas Fiscais Sankhya",
                "db_table": "sankhya_nota_fiscal",
                "ordering": ["-data_negociacao", "-numero_nota"],
            },
        ),
        migrations.CreateModel(
            name="ItemNotaFiscal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequencia", models.IntegerField(verbose_name="Sequência (SEQUENCIA)")),
                ("cod_produto", models.IntegerField(blank=True, null=True, verbose_name="Código Produto (CODPROD)")),
                ("quantidade", models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name="Quantidade (QTDNEG)")),
                ("valor_unitario", models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name="Valor Unitário (VLRUNIT)")),
                ("valor_total", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Valor Total (VLRTOT)")),
                ("uso_produto", models.CharField(blank=True, max_length=10, null=True, verbose_name="Uso Produto (USOPROD)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nota_fiscal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="api_sankhya.notafiscal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Nota Fiscal Sankhya",
                "verbose_name_plural": "Itens Nota Fiscal Sankhya",
                "db_table": "sankhya_item_nota_fiscal",
                "ordering": ["nota_fiscal", "sequencia"],
                "unique_together": {("nota_fiscal", "sequencia")},
            },
        ),
        migrations.AddIndex(
            model_name="notafiscal",
            index=models.Index(fields=["nunota"], name="sankhya_not_nunota_idx"),
        ),
        migrations.AddIndex(
            model_name="notafiscal",
            index=models.Index(fields=["codigo_empresa", "numero_nota"], name="sankhya_not_emp_num_idx"),
        ),
        migrations.AddIndex(
            model_name="notafiscal",
            index=models.Index(fields=["codigo_parceiro"], name="sankhya_not_parc_idx"),
        ),
        migrations.AddIndex(
            model_name="notafiscal",
            index=models.Index(fields=["data_negociacao"], name="sankhya_not_dtneg_idx"),
        ),
        migrations.AddIndex(
            model_name="notafiscal",
            index=models.Index(fields=["status_nfe"], name="sankhya_not_stnfe_idx"),
        ),
        migrations.AddIndex(
            model_name="itemnotafiscal",
            index=models.Index(fields=["nota_fiscal"], name="sankhya_itnf_nota_idx"),
        ),
        migrations.AddIndex(
            model_name="itemnotafiscal",
            index=models.Index(fields=["cod_produto"], name="sankhya_itnf_prod_idx"),
        ),
    ]
