# Generated by Django 5.0.14 on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_sankhya", "0029_notafiscal_itemnotafiscal"),
    ]

    operations = [
        migrations.AddField(
            model_name="notafiscal",
            name="codigo_vendedor",
            field=models.IntegerField(blank=True, null=True, verbose_name="Vendedor (CODVEND)"),
        ),
        migrations.AddIndex(
            model_name="notafiscal",
            index=models.Index(fields=["codigo_vendedor"], name="sankhya_not_vend_idx"),
        ),
    ]
