# Generated by Django 5.0.14 on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_sankhya", "0030_notafiscal_codigo_vendedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemnotafiscal",
            name="valor_desconto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Valor Desconto (VLRDESC)",
            ),
        ),
        migrations.AddField(
            model_name="itemnotafiscal",
            name="status_nota",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Status Nota (STATUSNOTA)",
            ),
        ),
    ]
