# Generated by Django 5.0.14 on 2026-08-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sankhya', '0036_grupoproduto_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCancelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nunota', models.IntegerField(unique=True, verbose_name='Nº único (NUNOTA)')),
                ('numero_nota', models.IntegerField(blank=True, null=True, verbose_name='Número NF (NUMNOTA)')),
                ('codigo_empresa', models.IntegerField(blank=True, null=True, verbose_name='Código Empresa (CODEMP)')),
                ('codigo_parceiro', models.IntegerField(blank=True, null=True, verbose_name='Parceiro (CODPARC)')),
                ('data_negociacao', models.DateField(blank=True, null=True, verbose_name='Data Negociação (DTNEG)')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data Cancelamento (DTCANC)')),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo Cancelamento (MOTCANCEL)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Nota Cancelada Sankhya',
                'verbose_name_plural': 'Notas Canceladas Sankhya',
                'db_table': 'sankhya_nota_cancelada',
                'ordering': ['-data_cancelamento', '-numero_nota'],
            },
        ),
        migrations.AddIndex(
            model_name='notacancelada',
            index=models.Index(fields=['codigo_empresa', 'numero_nota'], name='sankhya_not_codigo__0ee46e_idx'),
        ),
        migrations.AddIndex(
            model_name='notacancelada',
            index=models.Index(fields=['codigo_parceiro'], name='sankhya_not_codigo__7c9486_idx'),
        ),
        migrations.AddIndex(
            model_name='notacancelada',
            index=models.Index(fields=['data_cancelamento'], name='sankhya_not_data_ca_87dfc6_idx'),
        ),
    ]
